
--CREACI�N DE TABLAS
--13/05/20

CREATE TABLE EMPLEADO(
DNI CHAR(8) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(60) NOT NULL,
SEXO BIT NOT NULL ,--TRUE MASCULINO, FALSE FEMENINO
DIRECCION VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(13) NOT NULL,
CORREO VARCHAR(50) NULL,
ESTADO BIT NOT NULL
)
GO

CREATE TABLE CONTRATO(
NUMEROCONTRATO INT PRIMARY KEY,
FECHAINICIO DATE NOT NULL,
FECHAFIN DATE NOT NULL,
MONTO DECIMAL(8,2) NOT NULL,
VIGENCIA BIT NOT NULL,
HORASEXTRA BIT NOT NULL,
DNI CHAR(8) NOT NULL REFERENCES EMPLEADO
)
GO


CREATE TABLE HORARIO(
CODIGOHORARIO INT PRIMARY KEY,
FECHAINICIO DATE NOT NULL,
FECHAFIN DATE NULL,
ESTADO BIT NOT NULL,
DNI CHAR(8) NOT NULL REFERENCES EMPLEADO
)
GO

CREATE TABLE DETALLEHORARIO(
CODIGODETALLEHORARIO INT PRIMARY KEY,
CODIGOHORARIO INT NOT NULL REFERENCES HORARIO,
CODIGODIA TINYINT NOT NULL,
HORAENTRADA TINYINT NOT NULL,
HORASALIDA TINYINT NOT NULL
)
GO

CREATE TABLE ASISTENCIA(
CODIGOASISTENCIA INTEGER PRIMARY KEY,
FECHA DATE NOT NULL,
HORAENTRADA TIME NOT NULL,
HORASALIDA TIME NOT NULL,
DNI CHAR(8) NOT NULL REFERENCES EMPLEADO
)
GO

CREATE TABLE JUSTIFICACION(
CODIGOJUSTIFICACION INTEGER PRIMARY KEY,
FECHA DATE NOT NULL,
MOTIVO VARCHAR(50),
ESTADO BIT NOT NULL,
CODIGOASISTENCIA INTEGER NOT NULL REFERENCES ASISTENCIA
)
GO

--18/05/20

CREATE TABLE PERMISO (
CODIGOPERMISO INT PRIMARY KEY,
FECHAPRESENTACION DATE NOT NULL,
FECHAPERMISO DATE NOT NULL,
MOTIVO VARCHAR(100) NOT NULL,
ESTADO BIT NOT NULL,
DNI CHAR(8) NOT NULL REFERENCES EMPLEADO)
GO

CREATE TABLE TIPOLICENCIA(
CODIGOTIPOLICENCIA TINYINT PRIMARY KEY,
DESCRIPCION VARCHAR(50) NOT NULL,
MAXDIAS SMALLINT NOT NULL)
GO

CREATE TABLE LICENCIA (
NUMEROLICENCIA INTEGER PRIMARY KEY,
FECHAPRESENTACION DATE NOT NULL,
FECHAINICIO DATE NOT NULL,
FECHAFIN DATE NOT NULL,
ESTADO BIT NOT NULL,
DOCUMENTO VARCHAR(50) NOT NULL,
DNI CHAR(8) NOT NULL REFERENCES EMPLEADO,
CODIGOTIPOLICENCIA TINYINT NOT NULL REFERENCES TIPOLICENCIA)
GO

CREATE TABLE USUARIO(
CODIGOUSUARIO SMALLINT PRIMARY KEY,
NOMBRE VARCHAR (30) NOT NULL,
CONTRASEÑA VARCHAR(30) NOT NULL,
ESTADO BIT NOT NULL,
DNI CHAR(8) NOT NULL REFERENCES EMPLEADO
)
GO

INSERT INTO EMPLEADO VALUES('12345678','Juan','Perez Castro',1,'Panamericana 123','974763945','juan_pc@gmail.com',1);
INSERT INTO USUARIO VALUES (1,'Juanpc','123456',1,'12345678');