'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ASISTENCIA
    Public Property CODIGOASISTENCIA As Integer
    Public Property FECHA As Date
    Public Property HORAENTRADA As System.TimeSpan
    Public Property HORASALIDA As System.TimeSpan
    Public Property DNI As String

    Public Overridable Property EMPLEADO As EMPLEADO
    Public Overridable Property JUSTIFICACION As ICollection(Of JUSTIFICACION) = New HashSet(Of JUSTIFICACION)

End Class
