'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CONTRATO
    Public Property NUMEROCONTRATO As Integer
    Public Property FECHAINICIO As Date
    Public Property FECHAFIN As Date
    Public Property MONTO As Decimal
    Public Property VIGENCIA As Boolean
    Public Property HORASEXTRA As Boolean
    Public Property DNI As String

    Public Overridable Property EMPLEADO As EMPLEADO

End Class
