'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BDAsistenciaUsatEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BDAsistenciaUsatEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ASISTENCIA() As DbSet(Of ASISTENCIA)
    Public Overridable Property CONTRATO() As DbSet(Of CONTRATO)
    Public Overridable Property DETALLEHORARIO() As DbSet(Of DETALLEHORARIO)
    Public Overridable Property EMPLEADO() As DbSet(Of EMPLEADO)
    Public Overridable Property HORARIO() As DbSet(Of HORARIO)
    Public Overridable Property JUSTIFICACION() As DbSet(Of JUSTIFICACION)
    Public Overridable Property LICENCIA() As DbSet(Of LICENCIA)
    Public Overridable Property PERMISO() As DbSet(Of PERMISO)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property TIPOLICENCIA() As DbSet(Of TIPOLICENCIA)
    Public Overridable Property USUARIO() As DbSet(Of USUARIO)

End Class
