'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETALLEHORARIO
    Public Property CODIGODETALLEHORARIO As Integer
    Public Property CODIGOHORARIO As Integer
    Public Property CODIGODIA As Byte
    Public Property HORAENTRADA As Byte
    Public Property HORASALIDA As Byte

    Public Overridable Property HORARIO As HORARIO

End Class
