'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EMPLEADO
    Public Property DNI As String
    Public Property NOMBRE As String
    Public Property APELLIDO As String
    Public Property SEXO As Boolean
    Public Property DIRECCION As String
    Public Property TELEFONO As String
    Public Property CORREO As String
    Public Property ESTADO As Boolean

    Public Overridable Property ASISTENCIA As ICollection(Of ASISTENCIA) = New HashSet(Of ASISTENCIA)
    Public Overridable Property CONTRATO As ICollection(Of CONTRATO) = New HashSet(Of CONTRATO)
    Public Overridable Property HORARIO As ICollection(Of HORARIO) = New HashSet(Of HORARIO)
    Public Overridable Property LICENCIA As ICollection(Of LICENCIA) = New HashSet(Of LICENCIA)
    Public Overridable Property PERMISO As ICollection(Of PERMISO) = New HashSet(Of PERMISO)
    Public Overridable Property USUARIO As ICollection(Of USUARIO) = New HashSet(Of USUARIO)

End Class
