'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LICENCIA
    Public Property NUMEROLICENCIA As Integer
    Public Property FECHAPRESENTACION As Date
    Public Property FECHAINICIO As Date
    Public Property FECHAFIN As Date
    Public Property ESTADO As Boolean
    Public Property DOCUMENTO As String
    Public Property DNI As String
    Public Property CODIGOTIPOLICENCIA As Byte

    Public Overridable Property EMPLEADO As EMPLEADO
    Public Overridable Property TIPOLICENCIA As TIPOLICENCIA

End Class
