'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPOLICENCIA
    Public Property CODIGOTIPOLICENCIA As Byte
    Public Property DESCRIPCION As String
    Public Property MAXDIAS As Short

    Public Overridable Property LICENCIA As ICollection(Of LICENCIA) = New HashSet(Of LICENCIA)

End Class
