'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USUARIO
    Public Property CODIGOUSUARIO As Short
    Public Property NOMBRE As String
    Public Property CONTRASEÑA As String
    Public Property ESTADO As Boolean
    Public Property DNI As String

    Public Overridable Property EMPLEADO As EMPLEADO

End Class
